[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
lib_deps = adafruit/Adafruit NeoPixel@^1.12.0
monitor_speed = 9600
